Repository matrix-org/matrix.org, pull requests merged in 2023-11, with the labels that each got.

#2080 Update Matrix.org-SDKs Documentation
  content/ecosystem/sdks/index.md
Labels: guides

#2046 Display the clients homepage in client details
  static/assets/home.svg
  templates/ecosystem/client.html
Labels: enhancement

#2091 Add Commet to clients list
  content/ecosystem/clients/commet.md
  content/ecosystem/clients/commet.svg
Labels: projects

#2076 Fix some broken markdown links
  content/docs/matrix-concepts/end-to-end-encryption/_index.md
Labels: bug
