Repository matrix-org/matrix.org, pull requests merged in 2024-06, with the labels that each got.

#2359 Centre client project names that span 2 lines
  sass/_projects.scss
Labels: aesthetic

#2366 Add: (clients/ement.md) Ement.el
  content/ecosystem/clients/ement.md
  content/ecosystem/clients/ement.svg
Labels: ecosystem

#2357 Remove `overflow: hidden` on page headers
  sass/_base.scss
Labels: enhancement

#2347 Update twim-guide.md
  content/twim-guide.md
Labels: enhancement

#2338 Add elections page to a dropdown in the navigationbar
  content/foundation/_index.md
  content/foundation/about/amandine.jpg
  content/foundation/about/crowcroft.jpg
  content/foundation/about/denise.jpg
  content/foundation/about/guardians.toml
  content/foundation/about/index.md
  content/foundation/about/jim.jpg
  content/foundation/about/josh.jpg
  content/foundation/about/jutta.jpg
  content/foundation/about/matthew.jpg
  content/foundation/about/ross.jpg
  content/foundation/about/staff.toml
  content/foundation/about/thibault.jpg
  content/foundation/about/travis.jpg
  content/foundation/governing-board-elections/index.md
  content/foundation/governing-board-elections/nominees.toml
  navigation.toml
  sass/_header.scss
  templates/shortcodes/guardians.html
  templates/shortcodes/staff.html
Labels: enhancement

#2386 Fix ement.el breaking due to invalid html (a inside of a)
  .github/workflows/zola.yml
  templates/ecosystem/clients.html
Labels: ecosystem

#1954 Add Matrix.swift to list of SDKs
  content/ecosystem/sdks/sdks.toml
Labels: missing content
