Repository matrix-org/matrix.org, pull requests merged in 2024-01, with the labels that each got.

#2123 blog post detailing EMS migration to self-hosting
  content/blog/2024/01/2024-01-04-migrating-from-ems-to-selfhosted-matrix.md
  content/blog/2024/01/_index.md
  content/blog/2024/_index.md
Labels: guides, blog

#2121 Fix a missplaced space
  content/docs/older/stateres-v2.md
Labels: guides

#2132 Add Draupnir to the integrations list
  content/ecosystem/integrations/integrations.toml
Labels: projects

#2138 Zulip bridge
  content/ecosystem/bridges/zulip/_index.md
  content/ecosystem/bridges/zulip/bridges.toml
  content/ecosystem/bridges/zulip/logo.svg
Labels: projects

#2144 fix unhidden text on animation #2134
  templates/shortcodes/howitworks.html
Labels: bug, aesthetic
