Repository matrix-org/matrix.org, pull requests merged in 2024-02, with the labels that each got.

#2166 Add SDK: LibMatrix CSharp
  content/ecosystem/sdks/sdks.toml
Labels: projects

#2170 Publish FOSDEM wrap up
  content/blog/2024/02/2024-02-08-fosdem-wrap-up.md
  static/blog/img/fosdem2024-booth.jpg
  static/blog/img/fosdem2024-break-network.jpg
  static/blog/img/fosdem2024-devroom.jpg
  static/blog/img/fosdem2024-fringe.jpg
Labels: blog

#2175 Mark old IG/FB bridges as deprecated and add encryption feature to new bridge
  content/ecosystem/bridges/facebook_messenger/bridges.toml
  content/ecosystem/bridges/instagram/bridges.toml
Labels: projects

#2176 Add IndieHosters hosting provider
  content/ecosystem/hosting/providers.toml
  static/images/hosting/indiehosters.png
Labels: projects

#2177 Added fairkom to managed services providers
  content/ecosystem/hosting/providers.toml
  static/images/hosting/fairkom_4c_quer.svg
Labels: projects

#2165 Add spacing and alignment on mobile to the Supporters page
  sass/_support.scss
Labels: aesthetic

#2114 Update servers.toml
  content/ecosystem/servers/servers.toml
Labels: projects

#2192 fix: update maturity level of gomatrix SDK to "Obsolete"
  content/ecosystem/sdks/sdks.toml
Labels: projects

#2195 chore: move images next to markdown
  content/ecosystem/hosting/communick.png
  content/ecosystem/hosting/etke.cc.png
  content/ecosystem/hosting/fairkom_4c_quer.svg
  content/ecosystem/hosting/federated.png
  content/ecosystem/hosting/indiehosters.png
  content/ecosystem/hosting/logo-ems-primary.svg
  content/ecosystem/hosting/ossrox.svg
  content/ecosystem/hosting/ungleich_zerocarbonmatrix.jpg
  templates/shortcodes/hosting_providers.html
Labels: enhancement

#2199 Fix vertical centering of the matrix logo on matrix.org
  sass/_index.scss
Labels: aesthetic
