Repository matrix-org/matrix.org, pull requests merged in 2025-05, with the labels that each got.

#2719 remove leftover variable
  templates/index.html
Labels: bug

#2720 fix nameclash in navbar template page variable
  templates/includes/header.html
Labels: bug

#2723 TWIM 2025-05-02
  content/blog/2025/05/2025-05-02-twim.md
  content/blog/2025/05/_index.md
  static/blog/img/2025-05-02_Fractal.png
Labels: blog

#2717 launch 2025 GB elections landing page
  content/blog/2025/04/2025-04-28-election-announcement.md
  content/foundation/governing-board-elections/2024/index.md
  content/foundation/governing-board-elections/2024/nominees.toml
  content/foundation/governing-board-elections/2025/index.md
  content/foundation/governing-board-elections/2025/nominees.toml
  content/foundation/governing-board-elections/_index.md
  content/foundation/governing-board/index.md
Labels: meta

#2721 remove unused images
  content/foundation/about/jutta.jpg
Labels: bug

#2722 mark mx-puppet-bridges as obsolete
  content/ecosystem/bridges/groupme/bridges.toml
  content/ecosystem/bridges/slack/bridges.toml
Labels: ecosystem

#2742 Add v1.0 of the GB bylaws, take 2
  content/foundation/governing-board/bylaws/02-bylaws.md
  content/foundation/governing-board/bylaws/03-social-contract.md
  content/foundation/governing-board/bylaws/04-processes.md
  content/foundation/governing-board/bylaws/_index.md
  content/foundation/governing-board/index.md
Labels: governing board

#2724 Blog categories update and related misc fixes
  content/blog/2014/09/2014-09-09-techcrunch-update.md
  content/blog/2014/12/2014-12-24-matrix-wins-best-innovation-award-at-webrtc-paris.md
  content/blog/2015/01/2015-01-29-looking-forward-to-fosdem.md
  content/blog/2015/02/2015-02-04-back-from-fosdem.md
  content/blog/2015/05/2015-05-26-next-up-kamailio-world.md
  content/blog/2015/12/2015-12-14-webrtc-conference-expo-in-paris.md
  content/blog/2015/12/2015-12-25-the-matrix-holiday-special.md
  content/blog/2016/01/2016-01-18-fosdem-16.md
  content/blog/2016/02/2016-02-03-fosdem-16-retrospective.md
  content/blog/2016/03/2016-03-26-the-matrix-spring-special.md
  content/blog/2016/07/2016-07-04-the-matrix-summer-special.md
  content/blog/2016/11/2016-11-12-the-matrix-autumn-special.md
  content/blog/2016/12/2016-12-26-the-matrix-holiday-special-2016-edition.md
  content/blog/2017/02/2017-02-06-fosdem-2017-report.md
  content/blog/2017/10/2017-10-11-tadhack-global-2017-and-the-port-2017.md
  content/blog/2017/12/2017-12-25-the-matrix-holiday-mini-special-2017-edition.md
  content/blog/2018/02/2018-02-05-3d-video-calling-with-matrix-webrtc-and-webvr-at-fosdem-2018.md
  content/blog/2018/08/2018-08-31-so-long-half-shot-thanks-for-all-the-bridges.md
  content/blog/2018/12/2018-12-25-the-2018-matrix-holiday-special.md
  content/blog/2019/02/2019-02-04-matrix-at-fosdem-2019.md
  content/blog/2019/06/2019-06-11-synapse-1-0-0-released.md
  content/blog/2019/12/2019-12-24-the-2019-matrix-holiday-update.md
  content/blog/2020/01/2020-01-02-on-privacy-versus-freedom.md
  content/blog/2020/02/2020-02-03-matrix-at-fosdem-2020.md
  content/blog/2020/12/2020-12-25-the-matrix-holiday-special-2020.md
  content/blog/2021/01/2021-01-04-taking-fosdem-online-via-matrix.md
  content/blog/2021/02/2021-02-15-how-we-hosted-fosdem-2021-on-matrix.md
  content/blog/2021/12/2021-12-02-call-for-participation-for-the-fosdem-2022-matrix-dev-room.md
  content/blog/2021/12/2021-12-22-the-mega-matrix-holiday-special-2021.md
  content/blog/2022/02/2022-02-07-hosting-fosdem-2022-on-matrix.md
  content/blog/2022/08/2022-08-15-the-matrix-summer-special-2022.md
  content/blog/2022/11/2022-11-16-call-for-participation-for-the-fosdem-2023-matrix-devroom.md
  content/blog/2022/12/2022-12-25-the-matrix-holiday-update-2022.md
  content/blog/2023/02/2023-02-09-finally-a-hybrid-conference-that-worked.md
  content/blog/2023/07/2023-07-04-deportalling-libera-chat.md
  content/blog/2023/08/2023-08-04-libera-bridge-disabled.md
  content/blog/2023/11/2023-11-10-fosdem-cfp.md
  content/blog/2023/11/2023-11-28-liberachat.md
  content/blog/2023/12/2023-12-04-extension-fosdem-cfp.md
  content/blog/2023/12/2023-12-25-the-matrix-holiday-update-2023.md
  content/blog/2024/01/2024-01-11-matrix-presence-fosdem.md
  content/blog/2024/02/2024-02-08-fosdem-wrap-up.md
  content/blog/2024/06/2024-06-07-regulatory-update.md
  content/blog/2024/06/2024-06-12-matrix-conf-cfp.md
  content/blog/2024/08/2024-08-01-matrix-conf-schedule.md
  content/blog/2024/10/2024-10-29-matrixconf.md
  content/blog/2024/11/2024-11-04-fosdem-cfp.md
  content/blog/2024/11/2024-11-19-matrix-fosdem-full-force.md
  content/blog/2024/12/2024-12-25-the-matrix-holiday-update-2024.md
  content/blog/2025/02/2025-02-11-fosdem-wrap-up.md
  navigation.toml
  taxonomy.toml
  templates/blog.html
  templates/post.html
  templates/taxonomy_list.html
  templates/taxonomy_single.html
Labels: bug, enhancement

#2748 Update to v1.0.1 of the GB bylaws
  content/foundation/governing-board/bylaws/02-bylaws.md
  content/foundation/governing-board/bylaws/03-social-contract.md
  content/foundation/governing-board/bylaws/04-processes.md
  content/foundation/governing-board/index.md
Labels: governing board

#2765 Blog fixes
  content/blog/2025/05/2025-05-23-twim.md
  content/blog/2025/05/2025-05-25-governing-board-report-may-25.md
Labels: blog

#2734 Fix visualisation positioning on homepage
  sass/_index.scss
  templates/index.html
Labels: bug, aesthetic

#2763 Sort foundation members alphabetically in display
  templates/macros/supporters.html
  templates/support.html
Labels: bug, aesthetic, meta

#2767 Advertise MAS through the old MSC2965 discovery mechanism
  static/.well-known/matrix/client
Labels: homeserver
