Repository matrix-org/matrix.org, pull requests merged in 2025-04, with the labels that each got.

#2698 Name the Website and Content WG as repo maintainers instead of individuals
  CONTRIBUTING.md
  content/foundation/working-groups/working_groups.toml
Labels: wording, meta

#2692 Update Out Of Your Element feature set
  content/ecosystem/bridges/discord/bridges.toml
Labels: enhancement, ecosystem

#2708 Fixed icon colors: changed 4 SVG files to true black (#000000)
  static/assets/frontpage/bridge-visual.svg
  static/assets/frontpage/federation-visual-mobile.svg
  static/assets/frontpage/federation-visual.svg
  static/assets/frontpage/homeserver.svg
Labels: aesthetic

#2632 Add missing RSS feed, update zola
  config.toml
Labels: enhancement
