Repository matrix-org/matrix.org, pull requests merged in 2025-06, with the labels that each got.

#2772 Update contact.md
  content/contact.md
Labels: enhancement

#2768 Remove element wellknown for registration_helper_url
  static/.well-known/element/element.json
Labels: homeserver

#2782 Publish Premium Tiers blog post
  content/blog/2025/06/2025-06-11-funding-homeserver-premium.md
  static/blog/img/foundation-expenses-graph.png
  templates/membership.html
Labels: blog, meta

#2792 Fix up TWIM 2025-06-20
  content/blog/2025/06/2025-06-20-twim.md
Labels: blog

#2794 Update .well-known headers
  static/_headers
Labels: homeserver

#2795 Add Law Enforcement Guidelines Link to Footer
  navigation.toml
Labels: enhancement

#2800 TWIM 2025-06-27
  content/blog/2025/06/2025-06-27-twim.md
  static/blog/img/2025-06-27-fed-tester.png
  static/blog/img/2025-06-27-neoboard-arrows.png
  static/blog/img/2025-06-27-neoboard-stickies.png
Labels: blog
